name: FRP
version: '1.1'
main: tev.frp.FRP
authors: [ Tevuori ]

commands:
  repair:
    description: Toto vám za malý poplatek 50. coinů opraví vaše vypavení.
  gms:
    description: Toto vám změní gamemode na survival.
  gma:
    description: Toto vám změní gamemode na adventurer.
  gmc:
    description: Toto vám změní gamemode na creative.
  gmsp:
    description: Toto vám změní gamemode na spectator.
  spawn:
    description: Toto vás teleportuje na spawn.
  fly:
    description: Toto ti dá křídla